#!/usr/bin/env python3
import random
from docopt import docopt

from crylib.findconst import _constants_to_rules
from crylib.constants.CryptoConstants import constants as CryptoConstants
from crylib.constants.CryptoAPI import constants as CryptoAPIConstants

__doc__ = f"""Usage: crygen [-p PREFIX]

-h --help           Show this screen
"""

def main():
    arguments = docopt(__doc__)
    constants = CryptoConstants
    print(_constants_to_rules(constants, ['fullword', 'dword', 'qword']))

if __name__ == '__main__':
    main()
