#!/usr/bin/env python3
from docopt import docopt

from crylib import constants_to_rules
from crylib.constants.CryptoConstants import constants

__doc__ = """Usage: crygen [-e ENCODING]

-h --help           Show this screen
-e ENCODING         Encoding, could be : fullword,qword,dword or all [default: all]
"""


def main():
    arguments = docopt(__doc__)
    encoding = arguments['-e'].split(',')
    if arguments['-e'] == 'all':
        encoding = ['fullword', 'dword', 'qword']
    print(constants_to_rules(constants, encoding))


if __name__ == '__main__':
    main()
